### ISSUE TITLE
gRPC: Parser issue with semicolons in option(s) bloc

### ISSUE THREAD

**Issue by sir-farfan** [httpyac/httpyac.github.io#31]
Hello, thanks for this vsCode extension, it's been quite useful.

I added [openapiv2_swagger](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/protoc-gen-openapiv2/options/openapiv2.proto#L247) options to my .proto file, it builds correctly with protoc and generates the documentation.

The problem is, when I import it in httpYac `proto < health.proto`, the parser fails at every semicolon it finds: title, version, description... with a stacktrace like this:
```
Error: illegal name ';' (/me/project/client/health.proto, line 37)
	at g (/me/.vscode-server/extensions/anweber.vscode-httpyac-4.10.1/dist/extension.js:45:1533)
	at ge (/me/.vscode-server/extensions/anweber.vscode-httpyac-4.10.1/dist/extension.js:45:5965)
	at ge (/me/.vscode-server/extensions/anweber.vscode-httpyac-4.10.1/dist/extension.js:45:6037)
	at Z (/me/.vscode-server/extensions/anweber.vscode-httpyac-4.10.1/dist/extension.js:45:5859)
	at Wa (/me/.vscode-server/extensions/anweber.vscode-httpyac-4.10.1/dist/extension.js:45:7360)
	at u (/me/.vscode-server/extensions/anweber.vscode-httpyac-4.10.1/dist/extension.js:38:33301)
	at /me/.vscode-server/extensions/anweber.vscode-httpyac-4.10.1/dist/extension.js:38:33871
	at /me/.vscode-server/extensions/anweber.vscode-httpyac-4.10.1/dist/extension.js:38:312
	at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

I removed most of the semicolons, leaving only the one at the end of `option(...){...};` and now it works in both places, but I think it must parse just as protoc does... (?)

**Comment by AnWeber** [comment]
Could you please give me an example to reproduce the error. I just tested it with the following and didn't find the error directly during the init

```
# @name test
proto < ./openapiv2.proto
```

**Comment by AnWeber** [comment]
Okay, I think I got it. I need to comment out the option in the file. Right?
```
Error: illegal name ';' (openapiv2.proto, line 27)
    at illegal (C:\Users\weber\Desktop\httpyac\httpyac.github.io\examples\prototest\node_modules\protobufjs\src\parse.js:96:16)
    at parseOptionValue (C:\Users\weber\Desktop\httpyac\httpyac.github.io\examples\prototest\node_modules\protobufjs\src\parse.js:595:27)  
    at parseOptionValue (C:\Users\weber\Desktop\httpyac\httpyac.github.io\examples\prototest\node_modules\protobufjs\src\parse.js:604:33)  
    at parseOption (C:\Users\weber\Desktop\httpyac\httpyac.github.io\examples\prototest\node_modules\protobufjs\src\parse.js:585:27)       
    at parse (C:\Users\weber\Desktop\httpyac\httpyac.github.io\examples\prototest\node_modules\protobufjs\src\parse.js:783:17)
    at process (C:\Users\weber\Desktop\httpyac\httpyac.github.io\examples\prototest\node_modules\protobufjs\src\root.js:127:30)
    at C:\Users\weber\Desktop\httpyac\httpyac.github.io\examples\prototest\node_modules\protobufjs\src\root.js:194:17
    at fetchReadFileCallback (C:\Users\weber\Desktop\httpyac\httpyac.github.io\examples\prototest\node_modules\@protobufjs\fetch\index.js:51:19)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

But then I can more or less pass the error directly to @grpc-js/protoloader. I use this to parse proto files and it generates the error even without my extension.

```
const protoLoader = require('@grpc/proto-loader');

protoLoader.load('./openapiv2.proto', {}).then(packageDefinition => {
  console.info(packageDefinition);
}).catch(err => console.error(err));
```
[prototest.zip](https://github.com/httpyac/httpyac.github.io/files/8005882/prototest.zip)

**Comment by AnWeber** [comment]
Ok, someone was faster: https://github.com/protobufjs/protobuf.js/issues/1534

**Comment by sir-farfan** [comment]
Looks like I posted the issue in the wrong place?  : p

Yeah, that's exactly the issue.

**Comment by AnWeber** [comment]
Not a thing. You don't necessarily need to know what dependencies the code has. But I think it looks bad for a quick implementation. Soory. I will close the ticket. If protobufjs updates and fixes it, I'll update in a timely manner.  Do you agree?

**Comment by sir-farfan** [comment]
Sure, thanks : )

**Comment by AnWeber** [comment]
thx for using my extension:-)
