### ISSUE TITLE
error sending request

### ISSUE THREAD

**Issue by esasiyunx** [httpyac/httpyac.github.io#55]
hi, I would be very grateful if you could help me solve this problem.

RequestError: Cookie has domain set to the public suffix "localhost" which is a special use domain. To allow this, configure your CookieJar with {allowSpecialUseDomain:true, rejectPublicSuffixes: false}.
    at IS._destroy (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:67:20534)
    at _destroy (node:internal/streams/destroy:102:25)
    at IS.destroy (node:internal/streams/destroy:64:5)
    at /Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:67:2740
    at Object.xYe [as getPublicSuffix] (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:44:146717)
    at wYe (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:44:148339)
    at eb.findCookies (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:44:149896)
    at eb.findCookies (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:44:147801)
    at Ss.getCookies (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:62:11285)
    at Ss.getCookies (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:44:147801)
    at Ss.getCookieString (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:62:11638)
    at /Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:44:147935
    at new Promise (<anonymous>)
    at Ss.getCookieString (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:44:147835)
    at IS._makeRequest (/Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:67:15932)
    at /Users/aydinyildirim/.vscode/extensions/anweber.vscode-httpyac-5.6.3/dist/extension.js:67:2508
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by AnWeber** [comment]
@esasiyunx Have you just recently started having this error? `tough-cookie` accidentally introduced a breaking change (see https://github.com/salesforce/tough-cookie/issues/246) that forces exactly this setting for localhost. ~~I haven't integrated affected versions yet, so I'm surprised.~~ In vscode-httpyac I introduced the issue, stupid mistake (https://github.com/AnWeber/vscode-httpyac/blob/main/package-lock.json#L8067) Will fix it.

**Comment by AnWeber** [comment]
@esasiyunx I have provided a new version with the update from tought-cookie. Can you please test your use case as well. My problems with dependency are solved.

**Comment by esasiyunx** [comment]
yeap, the problem is fixed.

thx for help.

**Comment by esasiyunx** [comment]
not resolved with your change but i was able to fix it by turning this setting off

![Ekran Resmi 2022-08-26 01 00 03](https://user-images.githubusercontent.com/72391210/186776546-7c867816-becf-43a2-a4dc-4cade9f75024.png)

**Comment by AnWeber** [comment]
With the next release you can configure the CookieJar options directly. With this you could possibly experiment what triggers the error and how to avoid it.

**Comment by AnWeber** [comment]
v5.7.0 is released. Could you please try your use case again. You could noew configure CookieJar with setting `httpyac.cookieJarEnabled`
